server:
  port: 80

spring:
  application:
    name: mysns

  datasource:
    url: jdbc:sqlite:./data/db.db
    driver-class-name: org.sqlite.JDBC
    username: ""
    password: ""

  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/ # html 파일 경로
    suffix: .html
    cache: false

mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
